--Checklist 9
DROP TYPE tp_sala2 force;
DROP TABLE tb_sala2 force;

ALTER TYPE tp_clinica
ADD MEMBER FUNCTION metodo_abstrato RETURN NUMBER CASCADE;

ALTER TYPE tp_urgencia
ADD OVERRIDING MEMBER FUNCTION metodo_abstrato RETURN NUMBER CASCADE;

CREATE OR REPLACE TYPE BODY tp_urgencia AS
OVERRIDING MEMBER FUNCTION metodo_abstrato RETURN NUMBER IS
	BEGIN
		RETURN 1;
	END;
END;
/